dist: xenial
git:
  depth: false
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - doxygen-latex
      - libboost-all-dev
branches:
  except:
    - debian
compiler:
- gcc
- clang
language: cpp
env:
  global:
  - APT_DEPENDENCIES=""
  - LCOV_IGNORE_RULES="*tests* *examples*"
  - GH_USERNAME=gergondet
  - GH_REPO=jrl-umi3218/sch-core
  - secure: OqTZJoZqZagziaw+YqV6vD1+DzY7XpQLeTzYZZ/Q5ZnBKACxtK0Pg7iX2+cxhMsqoOYbnPr0CjDJR5pFKhAAH/cirDB96lBkT8j/EwrPjtHwqdn0vcPn1QPhn/xu87H/sAsr8IEEFiGbpRYlf2EoVzVsXp8z+VCFsFVNyqSNHxU=
  matrix:
    - CMAKE_BUILD_TYPE=RelWithDebInfo BUILD_BSD=OFF
    - CMAKE_BUILD_TYPE=RelWithDebInfo BUILD_BSD=ON GH_TOKEN=""
    - CMAKE_BUILD_TYPE=Debug BUILD_BSD=OFF GH_TOKEN=""
    - CMAKE_BUILD_TYPE=Debug BUILD_BSD=ON GH_TOKEN=""
notifications:
  slack:
    secure: SAnQfxV4qW1gGCZ+6cTOJ01b9GUxGHfr15QOLNp2ird4HoTNwpF+hSATGXhsYUrqaBlaC62dSi3TfMDMVrDHbTXzlgLAqPf46ZeKzjU+3tXvXPDNbfFIy5vd3xIJ0K61Jgvt2xZ5tHo89zRdorTHHQ9nALzAgm6FKeIyGzmL4Xs=
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install:
  - if [ $CC = gcc -a $CMAKE_BUILD_TYPE = RelWithDebInfo -a $BUILD_BSD = OFF ]; then export DO_DOC_UPDATE=true; else export DO_DOC_UPDATE=false; fi
  - export CMAKE_ADDITIONAL_OPTIONS="${CMAKE_ADDITIONAL_OPTIONS} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DBUILD_BSD:BOOL=${BUILD_BSD}"
  - ./.travis/run before_install
