language: cpp
compiler: gcc
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev"
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
  - debian
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install: ./.travis/run before_install
